spring:
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO
